version: '3.8'
services:
  app:
    container_name: hono_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'

  db:
      image: postgres:13
      container_name: postgres_db
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: postgres
        
      ports:
        - '5432:5432'
      volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
